### ISSUE TITLE
torchtext version

### ISSUE THREAD

**Issue by ggg66** [cyanbx/Frieren-V2A#1]
Please give me a version of torchtext. Thank you.

**Comment by cyanbx** [comment]
hi, I don't find where we use torchtext in this project, where do you use it?

**Comment by ggg66** [comment]
thanks  for your reply!
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import pytorch_lightning as pl
  File "/usr/local/python/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "/usr/local/python/lib/python3.8/site-packages/pytorch_lightning/metrics/__init__.py", line 15, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "/usr/local/python/lib/python3.8/site-packages/pytorch_lightning/metrics/classification/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "/usr/local/python/lib/python3.8/site-packages/pytorch_lightning/metrics/classification/accuracy.py", line 18, in <module>
    from pytorch_lightning.metrics.utils import deprecated_metrics, void
  File "/usr/local/python/lib/python3.8/site-packages/pytorch_lightning/metrics/utils.py", line 29, in <module>
    from pytorch_lightning.utilities import rank_zero_deprecation
  File "/usr/local/python/lib/python3.8/site-packages/pytorch_lightning/utilities/__init__.py", line 18, in <module>
    from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
  File "/usr/local/python/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py", line 31, in <module>
    from torchtext.legacy.data import Batch
ModuleNotFoundError: No module named 'torchtext.legacy'

**Comment by cyanbx** [comment]
Looks like it it called by pytorch-lightning. What's your pytorch-lightning version? We use 1.4.2

**Comment by ggg66** [comment]
my pytorch-lightning version is 1.4.2

**Comment by cyanbx** [comment]
I checked our environment and find that we don't have torchtext installed. You may search this error message somewhere else
